use_frameworks!

target 'PlayKitUtils_tvOS' do
    platform :tvos, '9.0'
    pod 'PlayKitUtils', :path => '../'
end

target 'PlayKitUtils_Tests' do
    platform :ios, '9.0'
    pod 'PlayKitUtils', :path => '../'
    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.3.4'
end
