use_frameworks!

target 'PlayKitUtils_tvOS' do
    platform :tvos, '9.0'
    pod 'PlayKitUtils', :path => '../'
end

target 'PlayKitUtils_Tests' do
    platform :ios, '8.0'
    pod 'PlayKitUtils', :path => '../'
    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            if target.name == 'PlayKitUtils'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
